export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENS_REQUEST = "GET_COMMENS_REQUEST";
export const GET_COMMENTS_REQUEST_FAIL = "GET_COMMENTS_REQUEST_FAIL";
export const COMMENT_CREATE = "COMMENT_CREATE";
export const COMMENT_DELETE = "COMMENT_DELETE";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const ADD_COMMENT_TO_POST = "ADD_COMMENT_TO_POST";
